# Generated by Django 5.0.3 on 2024-03-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_amount_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(upload_to='product_images/%Y/%m/'),
        ),
    ]
