# Generated by Django 5.0.2 on 2024-02-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_long',
            field=models.TextField(blank=True),
        ),
    ]
