# Generated by Django 5.0.2 on 2024-03-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_variation_product_alter_variation_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='slug',
        ),
    ]
